### ISSUE TITLE
Incorrect version specifier for pyqt5 in requirements.txt

### ISSUE THREAD

**Issue by Forklein** [xlmnxp/Qocker#1]
There is an issue with the version specifier for `pyqt5` in the `requirements.txt` file.

Currently, it is written as: pyqt5=5.15.10
This should be corrected to: pyqt5==5.15.10

Using a single `=` causes installation issues, as the correct syntax for specifying a package version in `requirements.txt` is `==`.

**Comment by xlmnxp** [comment]
Fixed 🫡, thank you
